name: Deploy to Hostinger

# Executa quando há push na branch master
on:
  push:
    branches: [master]
  workflow_dispatch: # Permite execução manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Baixar o código do GitHub
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Baixa todo o histórico
          
      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      # 3. Instalar dependências
      - name: Install dependencies
        run: npm ci
        
      # 4. Fazer build estático
      - name: Build static site
        run: npm run build:static
        
      # 5. Preparar arquivos para deploy
      - name: Prepare deploy files
        run: npm run deploy:copy
        
      # 6. Criar backup da versão atual (se existir)
      - name: Create backup of current version
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/app/
          server-dir: /public_html/admin/backup/$(date +%Y%m%d_%H%M%S)/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env*
        continue-on-error: true # Não falha se não houver backup anterior
        
      # 7. Deploy via FTP para Hostinger
      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/app/
          server-dir: /public_html/admin/app/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env*
            
      # 8. Deploy da API PHP
      - name: Deploy API to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/api/
          server-dir: /public_html/admin/api/
          exclude: |
            **/.git*
            **/.git*/**
            
      # 9. Testar se o site está funcionando
      - name: Test site health
        run: |
          echo "🧪 Testando se o site está funcionando..."
          sleep 10 # Aguarda deploy finalizar
          curl -f https://admin.meguispet.com/app/ || echo "⚠️ Site pode não estar funcionando"
          
      # 10. Notificar sucesso
      - name: Deploy Success
        run: |
          echo "✅ Deploy concluído com sucesso!"
          echo "🌐 Site: https://admin.meguispet.com/app/"
          echo "🔗 API: https://admin.meguispet.com/api/health"
          echo "📅 Versão: $(date +%Y-%m-%d_%H:%M:%S)"
          echo "📝 Commit: ${{ github.sha }}"
          echo "👤 Autor: ${{ github.actor }}"
