name: Rollback to Previous Version

# Executa apenas manualmente
on:
  workflow_dispatch:
    inputs:
      backup_version:
        description: 'Versão do backup para restaurar (ex: 20241201_143022)'
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Baixar o código do GitHub
      - name: Checkout code
        uses: actions/checkout@v4
        
      # 2. Restaurar backup
      - name: Restore from backup
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/app/
          server-dir: /public_html/admin/backup/${{ github.event.inputs.backup_version }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env*
            
      # 3. Deploy da versão restaurada
      - name: Deploy restored version
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/app/
          server-dir: /public_html/admin/app/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env*
            
      # 4. Notificar rollback
      - name: Rollback Success
        run: |
          echo "🔄 Rollback concluído com sucesso!"
          echo "🌐 Site: https://admin.meguispet.com/app/"
          echo "📅 Versão restaurada: ${{ github.event.inputs.backup_version }}"
          echo "👤 Executado por: ${{ github.actor }}"
